version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: codegames_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5433:5432'

  redis:
    image: redis:7
    ports:
      - '6380:6379'

  backend:
    build: ./backend
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
