version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: codegames
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  pgdata:
