services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - '5433:5432'

  backend:
    build: ./server
    env_file:
      - .env.test
    depends_on:
      - db
