version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - '5433:5432'

  redis:
    image: redis:7
    ports:
      - '6380:6379'

  backend:
    build: ./backend
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
